### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by depresonic** [ptrumpis/snap-camera-signature-patch#2]
Very sorry but im really need help... I do everything as described in the tutorial, but the application version 21 after the patch v3 just does not work (no preview filters, no search string, filters also do not work), after the previous patch application also does not work (but at least there were preview lenses in the application and the search string)... crc32 ok, I have Windows 10, if this is necessary information ... maybe you know how I solve this problem?

**Comment by depresonic** [comment]
Update... I was able to solve this problem with the preview and the search track, but there is another problem... The filters do not work. i.e. they are clickable and i can select them, but there is no change on the camera... unfortunately i am powerless here already, so i will be very glad if you can help to solve this problem

**Comment by ptrumpis** [comment]
You need to read https://github.com/ptrumpis/snap-camera-server/wiki/Updating-Snap-Camera-(Unofficial)

**Comment by depresonic** [comment]
> You need to read https://github.com/ptrumpis/snap-camera-server/wiki/Updating-Snap-Camera-(Unofficial)

Unfortunately, it didn't help me... Still none of the filters work :(

**Comment by depresonic** [comment]
Sorry if I'm talking out of line, I just don't understand it at all, but with your instructions I was able to install server 3, and now it even works for version 19 in my case. but now I have a problem of another nature with some lenses. the server does not feed them as shown in the picture (no orange text), could you please tell me if there is any way to solve this? I will attach a screenshot so you can understand what I am talking about. again sorry, I really do not understand your business, but really want to understand :)
![Screenshot_1](https://user-images.githubusercontent.com/127962762/225446736-8147bcc0-ed07-47be-9021-fb131dbdbf3d.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/127962762/225446741-35f458a2-0e8c-442b-b54d-d62980387191.jpg)

**Comment by ptrumpis** [comment]
I don't understand your problem and this is no longer related to the signature patch.

- The patch does not work with v1.19 therefore web lenses will not work
- All log messages are correct
- You didn't select the lens in the first screenshot, but you selected it in the second screenshot

**Comment by depresonic** [comment]
Nothing changes if I select the lens
![Screenshot_3](https://user-images.githubusercontent.com/127962762/225458899-870c6c2e-2b1e-4bc2-8937-c53d57dc0f99.jpg)

**Comment by depresonic** [comment]
Sorry if I confused you. I accidentally put in the same folder (C:\Program Files\Snap Inc\Snap Camera) version 19 (patch from jaku) and version 21 application (your patch). and now web lenses ( at least the link search works and now in version 19 I can find those lenses that did not come up in the search before) work the same for version 19, where my filters work. for version 21 web lenses work too, but filters do not apply (as I said above do not change image). I will attach screenshots.
![Screenshot_4](https://user-images.githubusercontent.com/127962762/225459551-59b7c65c-c6a5-4ccc-ba22
![Screenshot_8](https://user-images.githubusercontent.com/127962762/225459741-a602d504-36f8-4400-8bd9-06f53bf1fe94.jpg)
-5412e250b6c2.jpg)
![Screenshot_7](https://user-images.githubusercontent.com/127962762/225459612-1db0d3b9-ab60-48ac-9887-04cad3de3874.jpg)

**Comment by depresonic** [comment]
> Nothing changes if I select the lens ![Screenshot_3](https://user-images.githubusercontent.com/127962762/225458899-870c6c2e-2b1e-4bc2-8937-c53d57dc0f99.jpg)

Sorry for the endless stream of information that may have confused you. I just want to understand if it is possible to solve this problem that some lenses are not unlocked and not saved by the server 3 as shown in this screenshot

**Comment by ptrumpis** [comment]
You are mixing up too many things... You can not install 1.19 and 1.21 in the same folder.

It's impossible to tell what version you have installed right now, so it's impossible to help you..

My thoughts on this:
Why are you installing the outdated version 1.19? If you're using version 1.19, it's probably because 1.21 generally doesn't work on your system. In this case, neither the patch nor the server will be able to change anything.

**Comment by ptrumpis** [comment]
@depresonic I released a new patch for Snap Camera v1.19, this might fix your problem.
