### ISSUE TITLE
Error: application can't be opened

### ISSUE THREAD

**Issue by rahmat-dev** [ptrumpis/snap-camera-signature-patch#4]
I've followed the instructions step by step, but the application can't be opened. I can't find "Anywhere" option in the settings and I've running ```spctl``` and ```xattr``` commands.

![image](https://github.com/ptrumpis/snap-camera-signature-patch/assets/40190205/46476f23-d543-4460-bfd6-35ff85e797dd)

**Comment by ptrumpis** [comment]
> the application can't be opened

What error message are you getting?

**Comment by ptrumpis** [comment]
This might be helpful
- [If you can’t open an app on Mac](https://support.apple.com/en-gb/guide/mac-help/mchlp1519/mac)
- [Open a Mac app from an unidentified developer](https://support.apple.com/en-gb/guide/mac-help/mh40616/13.0/mac/13.0)

**Comment by rahmat-dev** [comment]
> > the application can't be opened
> 
> What error message are you getting?

![image](https://github.com/ptrumpis/snap-camera-signature-patch/assets/40190205/63b216b4-49ff-4064-863c-faaa6bf4d852)

**Comment by ptrumpis** [comment]
While searching for that error message I came across https://developer.apple.com/forums/thread/676627
Did you `chmod +x` the file after patching?

```
chmod +x "/Applications/Snap Camera.app/Contents/Mac OS/Snap Camera"
```

**Comment by Droppe1** [comment]
Hi, 

here https://macpaw.com/how-to/allow-apps-anywhere how to enable "anywhere" 

<img width="562" alt="Screenshot 2023-08-24 alle 10 08 34" src="https://github.com/ptrumpis/snap-camera-signature-patch/assets/140503444/55b203dc-0ac6-4687-9629-4b77a4f8ceaa">



But still the app doesn't open. 
I've got same error from the terminal: 

The application cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x60000253d920 {Error Domain=NSPOSIXErrorDomain Code=153 "Unknown error: 153" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}
<img width="703" alt="Screenshot 2023-08-24 alle 10 09 47" src="https://github.com/ptrumpis/snap-camera-signature-patch/assets/140503444/023456ac-2199-4bdb-a26f-7afc4d7f92fd">

**Comment by ptrumpis** [comment]
Try to open the app with Finder by right clicking and selecting "Open" from the context menu.

**Comment by Droppe1** [comment]
> Try to open the app with Finder by right clicking and selecting "Open" from the context menu.

doesn't work for me...

<img width="576" alt="Screenshot 2023-08-25 alle 11 57 16" src="https://github.com/ptrumpis/snap-camera-signature-patch/assets/140503444/42579983-56a8-40d1-8439-bbebe7b27257">

**Comment by ptrumpis** [comment]
This guide might help to fix the problem.

[Troubleshooting Mac OS](https://github.com/ptrumpis/snap-camera-server/wiki/Troubleshooting-Mac-OS)

Everything is explained more detailed.
If it doesn't fix the problem then currently there is no fix to the problem.
